### ISSUE TITLE
error in dispositioner.py - from yara import SyntaxError

### ISSUE THREAD

**Issue by bertyboy** [lmco/laikaboss#10]
I'm getting an error, seems to be related to yara (3.4 installed) 

dispositioner.py
from yara import SyntaxError
ImportError: cannot import name SyntaxError

full message:
ERROR:root:Import Exception for dispositioner.py module: ['Traceback (most recent call last):\n', '  File "/etc/laikaboss/laikaboss/modules/**init**.py", line 34, in <module>\n    _temp = __import__(module[:-3], locals(), globals(), [module[:-3].upper()], -1)\n', '  File "/etc/laikaboss/laikaboss/modules/dispositioner.py", line 20, in <module>\n    from yara import SyntaxError\n', 'ImportError: cannot import name SyntaxError\n']
Traceback (most recent call last):
  File "/etc/laikaboss/laikaboss/modules/**init**.py", line 34, in <module>
    _temp = __import__(module[:-3], locals(), globals(), [module[:-3].upper()], -1)
  File "/etc/laikaboss/laikaboss/modules/dispositioner.py", line 20, in <module>
    from yara import SyntaxError
ImportError: cannot import name SyntaxError
ERROR:root:Scan worker died, shutting down

**Comment by marnao** [comment]
You've likely got a syntax error in your disposition.yara file. Defaut path is etc/modules/disposition.yara. Try compiling/scanning with that rule file outside of laika and see if you get the same error.

**Comment by bertyboy** [comment]
Great thanks, it's working now.

I'd like to configure the output  - into some kind of logger, e.g logstash.

 for example I have Laika running on a graylog2 server. How do I get the ouput into fluentd so it can be analysed in graylog (elastic search)?

when  run a simple laika task, fluentd gives the error:

Log event failed emition. Will retry on next emition.
laikad: ERROR 7347|LOG_FLUENT||||Failed to flush buffer. Log events lost.

Thanks again

**Comment by marnao** [comment]
I have little to no experience with logstash/elasticsearch but some quick googling turns up an elasticsearch plugin for fluentd: https://github.com/uken/fluent-plugin-elasticsearch

You need an instance of fludentd (we like td-agent) for LOG_FLUENT to talk to, then using the elasticsearch plugin for fluent, you could forward the logs on to elasticsearch.

And alternative would be to use the LOG_FLUENT module as a guide to create a new module that takes a more direct route to getting data into elasticsearch and bypassing fluentd all together.

Hope this helps. I'm going to close this issue now.

**Comment by bertyboy** [comment]
Much appreciated.
