### ISSUE TITLE
TypeError from get_data() when processing a PE

### ISSUE THREAD

**Issue by louieamone** [lmco/laikaboss#13]
When processing a portable executable with out of the box Ubuntu configuration, I get the following error:

``` bash
$ python laika.py ../malware.zip | jq '.scan_result[] | { "file name" : .filename, "file type" : .fileType, "flags" : .flags, "md5" : .objectHash }'
ERROR:root:error on 19ac5658-3fd7-4c55-94ad-09054798e08e running module META_PE. exception details below: 0:00) ETA:  --:--:--
Traceback (most recent call last):
  File "/home/user/laikaboss-master/laikaboss/si_module.py", line 43, in run
    moduleResult = self._run(scanObject, result, depth, args)
  File "/home/user/laikaboss-master/laikaboss/modules/meta_pe.py", line 53, in _run
    moduleResult.append(ModuleObject(buffer=section.get_data(),externalVars=ExternalVars(filename=secName)))
TypeError: get_data() takes at least 2 arguments (1 given)
[snip results]
```

In this case, the PE is contained in a .zip.  I get the same error processing the PE by itself. In both cases, I still get the scan result.

I also tried running the FCIV executable from Microsoft through it and got the same result:

``` bash
$ python laika.py ../Windows-KB841290-x86-ENU.exe | jq '.scan_result[] | { "file name" : .filename, "file type" : .fileType, "flags" : .flags, "md5" : .objectHash }'
ERROR:root:error on 84121a80-9d90-4fb5-8980-c90dd867b194 running module META_PE. exception details below: 0:00) ETA:  --:--:--
Traceback (most recent call last):
  File "/home/user/laikaboss-master/laikaboss/si_module.py", line 43, in run
    moduleResult = self._run(scanObject, result, depth, args)
  File "/home/user/laikaboss-master/laikaboss/modules/meta_pe.py", line 53, in _run
    moduleResult.append(ModuleObject(buffer=section.get_data(),externalVars=ExternalVars(filename=secName)))
TypeError: get_data() takes at least 2 arguments (1 given)
100%[#######################################################] Processed: 1/1 total files (Elapsed Time: 0:00:00) Time: 0:00:00
{
  "md5": "58dc4df814685a165f58037499c89e76",
  "flags": [],
  "file type": [
    "pe",
    "cab"
  ],
  "file name": "../Windows-KB841290-x86-ENU.exe"
}
```

Did I miss something important in the setup?

Thanks!

**Comment by cfossace** [comment]
I get the same error depending on the files I use.

**Comment by mandeepsg** [comment]
I am also getting similar error while processing PDF or PPT file, mine is for the EXIFTOOL though

ERROR:root:error on 53741de8-2db6-4989-a831-4bbc832f0cc8 running module META_EXIFTOOL. exception details below:                                                           ] Processed: 0/1 total files (Elapsed Time: 0:09:59) ETA:  --:--:--
Traceback (most recent call last):
  File /laikaboss-master/laikaboss/si_module.py", line 43, in run
    moduleResult = self._run(scanObject, result, depth, args)
  File "/laikaboss-master/laikaboss/modules/meta_exiftool.py", line 46, in _run
    metaDict = et.get_metadata(temp_file_name)
  File "/laikaboss-master/modules/lib/exiftool.py", line 195, in __exit__
    self.terminate()
  File "/laikaboss-master/modules/lib/exiftool.py", line 184, in terminate
    self._process.stdin.write(b"-stay_open\nFalse\n")
IOError: [Errno 32] Broken pipe

Note: I do not have root access so running laikaboss as non root user

**Comment by mandeepsg** [comment]
Ok I fixed my issue after providing PERL5LIB path to the exiftool perl libs

Also we need to make sure that the exiftool executable should be defined in the PATH variable

**Comment by marnao** [comment]
The original issue related to pefile is due to an older version of the python pefile module being used. You can install the latest version with pip or something similar.

@mandeepsg glad you found your issue.

**Comment by jjs357** [comment]
Can the dockerfile for Laikaboss be fixed to provide this fix as well?
