### ISSUE TITLE
Permission Denied:  How to invoke laika?

### ISSUE THREAD

**Issue by cfossace** [lmco/laikaboss#17]
![image](https://cloud.githubusercontent.com/assets/8621171/10167359/33c1b9b8-6696-11e5-9b78-2d0edeea6906.png)

How do you recommend invoking laikaboss? I don't think the testfiles directory exists that is mentioned in README.md.

Not sure why this keeps saying permission denied. Do you have example pieces of malware we can run to try using laika? Using the download from Practical Malware Analysis.  I figured it would be good to scan since it unpacks a lot of malware. 
I have tried

./laika.py PracticalMalwareAnalysis-Lab.exe | jq -c . | (there was something else here)
./laika.py PracticalMalwareAnalysis-Lab.exe | jq -c 
./laika.py PracticalMalwareAnalysis-Lab.exe
./laika.py <PracticalMalwareAnalysis-Lab.exe> out.txt
./laika.py
python laika.py
python laikad.py

**Comment by marnao** [comment]
if you want to invoke laika.py as an executable you need to set the correct permissions on it..

chmod +x laika.py

or you could do:
python laika.py PracticalMalwareAnalysis-Lab.exe

**Comment by cfossace** [comment]
Thank you!! chmod worked. 

Is it possible to redirect the input/output into files?  When I try ./laika<malware.exe>laika.out it also gives permission denied. do I have to parse it with jq? 

I gave it all of the permissions possible lol

![image](https://cloud.githubusercontent.com/assets/8621171/10168615/94ed472a-669b-11e5-8cdf-58fdac137370.png)

**Comment by marnao** [comment]
yes, it's possible to redirect output, but that's not part of laikaboss. It depends on the shell you're using.

I think you're missing some fundamental knowledge of how to work on the command line. I would recommend brushing up with some youtube videos or introduction guides.

I'm going to close this thread since this isn't an issue with our software.
