### ISSUE TITLE
META_PE KeyError

### ISSUE THREAD

**Issue by jshlbrd** [lmco/laikaboss#35]
Receiving this KeyError in the META_PE module when trying to scan directories with the latest release:

ERROR:root:error on 63c576ee-3139-4f31-a560-be23b0061843 running module META_PE. exception details below: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/laikaboss-2.0-py2.7.egg/laikaboss/si_module.py", line 43, in run
    moduleResult = self._run(scanObject, result, depth, args)
  File "/usr/local/lib/python2.7/dist-packages/laikaboss-2.0-py2.7.egg/laikaboss/modules/meta_pe.py", line 83, in _run
    for imp_symbol in dump_dict['Imported symbols']:
KeyError: 'Imported symbols'

**Comment by jshlbrd** [comment]
Rolling back to commit 2d58bafbca1c2729c95d5422634952082b8b10de (before some META_PE changes) fixes the error.

**Comment by marnao** [comment]
Thanks Josh.

I'll give @mtmcgrew an opportunity to fix it since it was his code. Looks like an easy one.

If he doesn't get around to it in a few days then I'll take care of it.

**Comment by jshlbrd** [comment]
Thanks!

**Comment by jshlbrd** [comment]
Wrong button. :)
