### ISSUE TITLE
Problem with pefile

### ISSUE THREAD

**Issue by bieronym** [lmco/laikaboss#45]
The link at the desciption doesn't work 
wget http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz
When i clone the pefile version that exists now on git, i get warnings when running laika.py
Solve it when downloading the exact version from here 
wget http://pkgs.fedoraproject.org/repo/pkgs/python-pefile/pefile-1.2.10-139.tar.gz/f10a94320bfaca356fff4d28c41e9278/pefile-1.2.10-139.tar.gz

**Comment by knowmalware** [comment]
Should use the archive from the official repo on github:
  https://github.com/erocarrera/pefile/archive/pefile-1.2.10-139.zip

The problem with current code in pefile repo is detailed in erocarrera/pefile#130 with suggested fixes

**Comment by SaiGonSeamus** [comment]
On debian Jessie I'm getting this error with pefile build.

root@OTX:~/pyexiftool-master/pefile-pefile-1.2.10-139# python setup.py build
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import pefile
  File "/root/pyexiftool-master/pefile-pefile-1.2.10-139/pefile.py", line 25, in <module>
    **version** = '1.2.10-%d' % int( **revision**[21:-2] )
ValueError: invalid literal for int() with base 10: ''

Is this the same issue?

**Comment by knowmalware** [comment]
That is a different problem.  You just have to change the

``` python
version = '1.2.10-%d' % int( revision[21:-1] )
```

line to

``` python
version = '1.2.10-139'
```

to get it past that for now.

See my comment on #47 if you want to script this.
