### ISSUE TITLE
Install Instructions for CentOS 7.1

### ISSUE THREAD

**Issue by dcode** [lmco/laikaboss#5]
I created a gist that has instructions on how to get this working on CentOS 7.x. The only piece that is missing from the default repos is Yara and unrar. I created RPMs for those and put it into a Package Cloud, free repo (included in the instructions).

https://gist.github.com/dcode/a828034a883cc06634f9

**Comment by marnao** [comment]
Thanks! We've got something similar in the readme now. If you want to make any tweaks feel free to submit a PR.
