### ISSUE TITLE
Active project?

### ISSUE THREAD

**Issue by geekscrapy** [lmco/laikaboss#78]
Hey, is this project still in dev?

TIA!

**Comment by agrajag9** [comment]
ping @marnao

**Comment by marnao** [comment]
just a couple years late on this but we are rewriting Laika BOSS for python 3 and hope to release it later this year... as @agrajag9 has said elsewhere, there are viable alternatives if you don't want to wait :)

**Comment by geekscrapy** [comment]
Ooo interesting... I'll wait 🙃

Can you update here when it's released please?!!
