### ISSUE TITLE
Network Instance Questions

### ISSUE THREAD

**Issue by bosslabdcu** [lmco/laikaboss#80]
Hello, I am a student who is using laikaboss

I have a question about network instances and distributed processing.

As far as I'm concerned, 
According to the white paper, laikaboss has brokers and walkers, which makes it faster.

If what I understand is correct, the more walkers, the faster the file scanning should be.
However, the more walkers there are, the slower it seems.

Do you happen to know the solution?

-----------------------------------------------------------------

The composition of my experiment is as follows.

broker: ./laikad.py --broker-frontend=tcp://*:5558 --broker-backend=tcp://*:5559 --worker-connect=tcp://localhost:5559 -p 8

Client: ./cloudscan.py ~/FILE PATH/ -R -r -a tcp://"brokerIP:5559"

worker1: ./laikad.py --no-broker --worker-connect=tcp://brokerIP:5559 -a -p 8
worker2: ./laikad.py --no-broker --worker-connect=tcp://brokerIP:5559 -a -p 8
worker3: ./laikad.py --no-broker --worker-connect=tcp://brokerIP:5559 -a -p 8

-----------------------------------------------------------------
Thank you.

**Comment by agrajag9** [comment]
There really isn't enough context here about the underlying systems you're running this on.

Also, LaikaBOSS is basically abandonware now 😢 . Try out Target/Strelka, which is ostensibly a fork.

**Comment by bosslabdcu** [comment]
@agrajag9 

thank you
